"services":
  "example-deployment":
    "build": "./example-deployment/."
    "container_name": "example-deployment"
    "environment":
      "MESSAGE": "jam the funk"
    "image": "xmconstantx/example-deployment"
    "platform": "linux/amd64"
    "ports":
    - "3000:3000"
