services:
  akash-deploy:
    build: .
    entrypoint: ./entrypoint.sh
    environment:
      AKASH_SEED_PHRASE: $AKASH_SEED_PHRASE
      AKASH_KEY_NAME: $AKASH_KEY_NAME
      AKASH_KEYRING_PASSPHRASE: $AKASH_KEYRING_PASSPHRASE
      TF_ORG_NAME: $TF_ORG_NAME
      TF_TOKEN_app_terraform_io: $TF_TOKEN_app_terraform_io
  akash-destroy:
    build: .
    entrypoint: ./destroy.sh
    environment:
      AKASH_SEED_PHRASE: $AKASH_SEED_PHRASE
      AKASH_KEY_NAME: $AKASH_KEY_NAME
      AKASH_KEYRING_PASSPHRASE: $AKASH_KEYRING_PASSPHRASE
      TF_ORG_NAME: $TF_ORG_NAME
      TF_TOKEN_app_terraform_io: $TF_TOKEN_app_terraform_io